const { GOOGLE, FACEBOOK, LOCAL } = require("./constants");

module.exports = {
    BCRYPT_SALT_ROUNDS: 12,
    BCRYPT_MAX_BYTES: 72,
    ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
    SESSION_TOKEN_SECRET: process.env.SESSION_TOKEN_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    IMGBB_API_KEY: process.env.IMGBB_API_KEY,
    FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
    FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
    AUTH_PROVIDERS: [GOOGLE, FACEBOOK, LOCAL],
};
